# Claude Code agent shells get env from snapshots — skip redundant work
[[ -n "$CLAUDECODE" ]] && return

# Homebrew — cached env (generated by install.sh)
local _brew_cache="$HOME/.cache/zsh/init/brew.zsh"
if [[ -f "$_brew_cache" ]]; then
    source "$_brew_cache"
elif [[ -x /opt/homebrew/bin/brew ]]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
elif [[ -x /usr/local/bin/brew ]]; then
    eval "$(/usr/local/bin/brew shellenv)"
fi

