typeset -U path

# Homebrew — cached env (generated by install.sh); inherited shells already have it set
local _brew_cache="$HOME/.cache/zsh/init/brew.zsh"
if [[ -z "$HOMEBREW_PREFIX" ]]; then
    if [[ -f "$_brew_cache" ]]; then
        source "$_brew_cache"
    elif [[ -x /opt/homebrew/bin/brew ]]; then
        eval "$(/opt/homebrew/bin/brew shellenv)"
    elif [[ -x /usr/local/bin/brew ]]; then
        eval "$(/usr/local/bin/brew shellenv)"
    fi
fi

# Keep brew ahead of /usr/bin: macOS path_helper (/etc/zprofile, login shells) rebuilds
# PATH system-first. typeset -U dedups, so this just moves brew to the front.
[[ -n "$HOMEBREW_PREFIX" ]] && path=("$HOMEBREW_PREFIX/bin" "$HOMEBREW_PREFIX/sbin" $path)

export HOMEBREW_NO_ENV_HINTS=1
export EDITOR="${EDITOR:-vim}"
export VISUAL="${VISUAL:-vim}"

# Agent shells parse output - keep it deterministic regardless of any tool's color config
[[ -n "$CLAUDECODE" ]] && export NO_COLOR=1

[[ -f "$HOME/.local/bin/env" ]] && . "$HOME/.local/bin/env"

# User overrides (not in repo)
[[ -f ~/.env.zsh ]] && source ~/.env.zsh
