typeset -U path

# Homebrew — cached env (generated by install.sh)
local _brew_cache="$HOME/.cache/zsh/init/brew.zsh"
if [[ -z "$HOMEBREW_PREFIX" ]]; then
    if [[ -f "$_brew_cache" ]]; then
        source "$_brew_cache"
    elif [[ -x /opt/homebrew/bin/brew ]]; then
        eval "$(/opt/homebrew/bin/brew shellenv)"
    elif [[ -x /usr/local/bin/brew ]]; then
        eval "$(/usr/local/bin/brew shellenv)"
    fi
fi

export HOMEBREW_NO_ENV_HINTS=1
export EDITOR="${EDITOR:-vim}"
export VISUAL="${VISUAL:-vim}"

[[ -f "$HOME/.local/bin/env" ]] && . "$HOME/.local/bin/env"

# User overrides (not in repo)
[[ -f ~/.env.zsh ]] && source ~/.env.zsh
